### ISSUE TITLE
Reference for your quantum_reinforcement_learning?

### ISSUE THREAD

**Issue by ghost** [stefan-woerner/quantum_reinforcement_learning#2]
Hello @stefan-woerner,

  Could you tell me your reference for your quantum reinforcement learning in this folder?

   Thanks!

**Comment by stefan-woerner** [comment]
Hi @cubicgate, I think what we looked at back then was this paper here: https://arxiv.org/pdf/1907.00397.pdf

**Comment by ghost** [comment]
Thanks @stefan-woerner!
